version: '3.8'

services:
  spoolman:
    image: spoolman-openspool:0.26.1
    build:
      context: https://github.com/sitnikovv/Spoolman.git#deploy/openspool-qr-nas
      dockerfile: Dockerfile.openspool
      args:
        SPOOLMAN_VERSION: '0.26.1'
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data
        target: /home/app/.local/share/spoolman
    ports:
      - '7912:8000'
    environment:
      - TZ=Europe/Moscow
